/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GdriveAuthRouteImport } from './routes/gdrive-auth'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LawyerSlugRouteImport } from './routes/lawyer.$slug'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppFilesRouteImport } from './routes/_app.files'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAiRouteImport } from './routes/_app.ai'
import { Route as AppFinanceIndexRouteImport } from './routes/_app.finance.index'
import { Route as AppCasesIndexRouteImport } from './routes/_app.cases.index'
import { Route as AppFinanceNewRouteImport } from './routes/_app.finance.new'
import { Route as AppCasesNewRouteImport } from './routes/_app.cases.new'
import { Route as AppFinancePaymentIdIndexRouteImport } from './routes/_app.finance.$paymentId.index'
import { Route as AppCasesCaseIdIndexRouteImport } from './routes/_app.cases.$caseId.index'
import { Route as AppCasesCaseIdEditRouteImport } from './routes/_app.cases.$caseId.edit'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GdriveAuthRoute = GdriveAuthRouteImport.update({
  id: '/gdrive-auth',
  path: '/gdrive-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LawyerSlugRoute = LawyerSlugRouteImport.update({
  id: '/lawyer/$slug',
  path: '/lawyer/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppFilesRoute = AppFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceIndexRoute = AppFinanceIndexRouteImport.update({
  id: '/finance/',
  path: '/finance/',
  getParentRoute: () => AppRoute,
} as any)
const AppCasesIndexRoute = AppCasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceNewRoute = AppFinanceNewRouteImport.update({
  id: '/finance/new',
  path: '/finance/new',
  getParentRoute: () => AppRoute,
} as any)
const AppCasesNewRoute = AppCasesNewRouteImport.update({
  id: '/cases/new',
  path: '/cases/new',
  getParentRoute: () => AppRoute,
} as any)
const AppFinancePaymentIdIndexRoute =
  AppFinancePaymentIdIndexRouteImport.update({
    id: '/finance/$paymentId/',
    path: '/finance/$paymentId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppCasesCaseIdIndexRoute = AppCasesCaseIdIndexRouteImport.update({
  id: '/cases/$caseId/',
  path: '/cases/$caseId/',
  getParentRoute: () => AppRoute,
} as any)
const AppCasesCaseIdEditRoute = AppCasesCaseIdEditRouteImport.update({
  id: '/cases/$caseId/edit',
  path: '/cases/$caseId/edit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gdrive-auth': typeof GdriveAuthRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/ai': typeof AppAiRoute
  '/dashboard': typeof AppDashboardRoute
  '/files': typeof AppFilesRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/lawyer/$slug': typeof LawyerSlugRoute
  '/cases/new': typeof AppCasesNewRoute
  '/finance/new': typeof AppFinanceNewRoute
  '/cases/': typeof AppCasesIndexRoute
  '/finance/': typeof AppFinanceIndexRoute
  '/cases/$caseId/edit': typeof AppCasesCaseIdEditRoute
  '/cases/$caseId/': typeof AppCasesCaseIdIndexRoute
  '/finance/$paymentId/': typeof AppFinancePaymentIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gdrive-auth': typeof GdriveAuthRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/ai': typeof AppAiRoute
  '/dashboard': typeof AppDashboardRoute
  '/files': typeof AppFilesRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/lawyer/$slug': typeof LawyerSlugRoute
  '/cases/new': typeof AppCasesNewRoute
  '/finance/new': typeof AppFinanceNewRoute
  '/cases': typeof AppCasesIndexRoute
  '/finance': typeof AppFinanceIndexRoute
  '/cases/$caseId/edit': typeof AppCasesCaseIdEditRoute
  '/cases/$caseId': typeof AppCasesCaseIdIndexRoute
  '/finance/$paymentId': typeof AppFinancePaymentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gdrive-auth': typeof GdriveAuthRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/_app/ai': typeof AppAiRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/files': typeof AppFilesRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/profile': typeof AppProfileRoute
  '/lawyer/$slug': typeof LawyerSlugRoute
  '/_app/cases/new': typeof AppCasesNewRoute
  '/_app/finance/new': typeof AppFinanceNewRoute
  '/_app/cases/': typeof AppCasesIndexRoute
  '/_app/finance/': typeof AppFinanceIndexRoute
  '/_app/cases/$caseId/edit': typeof AppCasesCaseIdEditRoute
  '/_app/cases/$caseId/': typeof AppCasesCaseIdIndexRoute
  '/_app/finance/$paymentId/': typeof AppFinancePaymentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/forgot-password'
    | '/gdrive-auth'
    | '/login'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/ai'
    | '/dashboard'
    | '/files'
    | '/notifications'
    | '/profile'
    | '/lawyer/$slug'
    | '/cases/new'
    | '/finance/new'
    | '/cases/'
    | '/finance/'
    | '/cases/$caseId/edit'
    | '/cases/$caseId/'
    | '/finance/$paymentId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/forgot-password'
    | '/gdrive-auth'
    | '/login'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/ai'
    | '/dashboard'
    | '/files'
    | '/notifications'
    | '/profile'
    | '/lawyer/$slug'
    | '/cases/new'
    | '/finance/new'
    | '/cases'
    | '/finance'
    | '/cases/$caseId/edit'
    | '/cases/$caseId'
    | '/finance/$paymentId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/contact'
    | '/forgot-password'
    | '/gdrive-auth'
    | '/login'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/_app/ai'
    | '/_app/dashboard'
    | '/_app/files'
    | '/_app/notifications'
    | '/_app/profile'
    | '/lawyer/$slug'
    | '/_app/cases/new'
    | '/_app/finance/new'
    | '/_app/cases/'
    | '/_app/finance/'
    | '/_app/cases/$caseId/edit'
    | '/_app/cases/$caseId/'
    | '/_app/finance/$paymentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GdriveAuthRoute: typeof GdriveAuthRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  LawyerSlugRoute: typeof LawyerSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gdrive-auth': {
      id: '/gdrive-auth'
      path: '/gdrive-auth'
      fullPath: '/gdrive-auth'
      preLoaderRoute: typeof GdriveAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lawyer/$slug': {
      id: '/lawyer/$slug'
      path: '/lawyer/$slug'
      fullPath: '/lawyer/$slug'
      preLoaderRoute: typeof LawyerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/files': {
      id: '/_app/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof AppFilesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai': {
      id: '/_app/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance/': {
      id: '/_app/finance/'
      path: '/finance'
      fullPath: '/finance/'
      preLoaderRoute: typeof AppFinanceIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cases/': {
      id: '/_app/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof AppCasesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance/new': {
      id: '/_app/finance/new'
      path: '/finance/new'
      fullPath: '/finance/new'
      preLoaderRoute: typeof AppFinanceNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cases/new': {
      id: '/_app/cases/new'
      path: '/cases/new'
      fullPath: '/cases/new'
      preLoaderRoute: typeof AppCasesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance/$paymentId/': {
      id: '/_app/finance/$paymentId/'
      path: '/finance/$paymentId'
      fullPath: '/finance/$paymentId/'
      preLoaderRoute: typeof AppFinancePaymentIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cases/$caseId/': {
      id: '/_app/cases/$caseId/'
      path: '/cases/$caseId'
      fullPath: '/cases/$caseId/'
      preLoaderRoute: typeof AppCasesCaseIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cases/$caseId/edit': {
      id: '/_app/cases/$caseId/edit'
      path: '/cases/$caseId/edit'
      fullPath: '/cases/$caseId/edit'
      preLoaderRoute: typeof AppCasesCaseIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAiRoute: typeof AppAiRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFilesRoute: typeof AppFilesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppCasesNewRoute: typeof AppCasesNewRoute
  AppFinanceNewRoute: typeof AppFinanceNewRoute
  AppCasesIndexRoute: typeof AppCasesIndexRoute
  AppFinanceIndexRoute: typeof AppFinanceIndexRoute
  AppCasesCaseIdEditRoute: typeof AppCasesCaseIdEditRoute
  AppCasesCaseIdIndexRoute: typeof AppCasesCaseIdIndexRoute
  AppFinancePaymentIdIndexRoute: typeof AppFinancePaymentIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiRoute: AppAiRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFilesRoute: AppFilesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppCasesNewRoute: AppCasesNewRoute,
  AppFinanceNewRoute: AppFinanceNewRoute,
  AppCasesIndexRoute: AppCasesIndexRoute,
  AppFinanceIndexRoute: AppFinanceIndexRoute,
  AppCasesCaseIdEditRoute: AppCasesCaseIdEditRoute,
  AppCasesCaseIdIndexRoute: AppCasesCaseIdIndexRoute,
  AppFinancePaymentIdIndexRoute: AppFinancePaymentIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GdriveAuthRoute: GdriveAuthRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  LawyerSlugRoute: LawyerSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
