// This file is automatically generated. Do not edit it directly.
/* eslint-disable @typescript-eslint/no-explicit-any */
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

export function isSupabaseConfigured(): boolean {
  const SUPABASE_URL =
    typeof import.meta !== "undefined" && import.meta.env
      ? import.meta.env.VITE_SUPABASE_URL
      : typeof process !== "undefined"
        ? process.env.SUPABASE_URL
        : undefined;

  const SUPABASE_PUBLISHABLE_KEY =
    typeof import.meta !== "undefined" && import.meta.env
      ? import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY
      : typeof process !== "undefined"
        ? process.env.SUPABASE_PUBLISHABLE_KEY
        : undefined;

  return !!(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);
}

function createDummySupabaseClient() {
  console.warn("[Supabase] Returning a mock/stub client because environment keys are missing.");
  const dummyAuth = {
    onAuthStateChange: (cb: any) => {
      setTimeout(() => cb("SIGNED_OUT", null), 0);
      return {
        data: {
          subscription: {
            unsubscribe: () => {},
          },
        },
      };
    },
    getSession: async () => {
      return { data: { session: null }, error: null };
    },
    getUser: async () => {
      return { data: { user: null }, error: null };
    },
    signOut: async () => {
      return { error: null };
    },
    signInWithPassword: async () => {
      return {
        data: { user: null, session: null },
        error: new Error("Supabase is not configured."),
      };
    },
    signUp: async () => {
      return {
        data: { user: null, session: null },
        error: new Error("Supabase is not configured."),
      };
    },
  };

  const dummyClient = new Proxy({ auth: dummyAuth } as any, {
    get(target, prop, receiver) {
      if (prop === "auth") {
        return dummyAuth;
      }
      if (prop === "from") {
        return () => {
          const tableChain = {
            select: () => tableChain,
            insert: () => tableChain,
            update: () => tableChain,
            delete: () => tableChain,
            eq: () => tableChain,
            neq: () => tableChain,
            order: () => tableChain,
            limit: () => tableChain,
            single: () =>
              Promise.resolve({ data: null, error: new Error("Supabase is not configured.") }),
            maybeSingle: () =>
              Promise.resolve({ data: null, error: new Error("Supabase is not configured.") }),
            then: (resolve: any) => resolve({ data: [], error: null }),
          };
          return tableChain;
        };
      }
      return Reflect.get(target, prop, receiver);
    },
  });

  return dummyClient;
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Please connect your Supabase project in Vercel.`;
    console.error(`[Supabase] ${message}`);
    // Return dummy client instead of hard throwing to prevent React blank white screen crash
    return createDummySupabaseClient() as any;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
